# author:
#   name: Leo
#   email: mail@nleo.me
  
title: nLeo.me
description: "Copyright © 2023 nLeo.\nAll rights reserved.\nPowered by Github Pages."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nleo.me" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: G-XMC20VWYEH

# theme: minima
remote_theme: jekyll/minima
minima:
  skin: auto
  date_format: "%b %-d, %Y"
  social_links:
    - { platform: github,  user_url: "https://github.com/1993hzh" }
    - { platform: linkedin, user_url: "https://linkedin.com/in/1993hzh" }

disqus:
    shortname: nleo
paginate: 5
paginate_path: "/posts/page:num/"
show_excerpts: true
header_pages:
  - about.md
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
markdown: kramdown
highlighter: coderay
kramdown:
  input: GFM
  syntax_highlighter: coderay
#   syntax_highlighter_opts:
#     line_numbers: table
#     bold_every: 10
#     tab_width: 2

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
